import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('your_database.db')
cursor = conn.cursor()



# Create the "classes" table if it doesn't exist
cursor.execute('''CREATE TABLE IF NOT EXISTS classes (
                    subject TEXT,
                    class_name TEXT
                )''')

# Define the classes and subjects

class_data = [
    ('Business', 'Accounting'),
    ('Business', 'Business law'),
    ('Business', 'Business management'),
    ('Business', 'Consumer education'),
    ('Business', 'Entrepreneurial skills'),
    ('Business', 'Introduction to business'),
    ('Business', 'Marketing'),
    ('Business', 'Personal finance'),
    ('Computer Science/Information Technology', 'Animation'),
    ('Computer Science/Information Technology', 'App development'),
    ('Computer Science/Information Technology', 'Audio production'),
    ('Computer Science/Information Technology', 'Computer programming'),
    ('Computer Science/Information Technology', 'Computer repair'),
    ('Computer Science/Information Technology', 'Film production'),
    ('Computer Science/Information Technology', 'Graphic design'),
    ('Computer Science/Information Technology', 'Media technology'),
    ('Computer Science/Information Technology', 'Music production'),
    ('Computer Science/Information Technology', 'Typing'),
    ('Computer Science/Information Technology', 'Video game development'),
    ('Computer Science/Information Technology', 'Web design'),
    ('Computer Science/Information Technology', 'Web programming'),
    ('Computer Science/Information Technology', 'Word processing'),
    ('English', 'American literature'),
    ('English', 'British literature'),
    ('English', 'Contemporary literature'),
    ('English', 'Creative writing'),
    ('English', 'Communication skills'),
    ('English', 'Debate'),
    ('English', 'English language and composition'),
    ('English', 'English literature and composition'),
    ('English', 'Humanities'),
    ('English', 'Journalism'),
    ('English', 'Literary analysis'),
    ('English', 'Modern literature'),
    ('English', 'Poetry'),
    ('English', 'Popular literature'),
    ('English', 'Rhetoric'),
    ('English', 'Technical writing'),
    ('English', 'Works of Shakespeare'),
    ('English', 'World literature'),
    ('English', 'Written and oral communication'),
    ('English', 'AP English Language and Composition'),
    ('English', 'AP English Literature and Composition'),
    ('Family and Consumer Science', 'Chemistry of foods'),
    ('Family and Consumer Science', 'CPR training'),
    ('Family and Consumer Science', 'Culinary arts'),
    ('Family and Consumer Science', 'Early childhood development'),
    ('Family and Consumer Science', 'Early childhood education'),
    ('Family and Consumer Science', 'Family studies'),
    ('Family and Consumer Science', 'Fashion and retail merchandising'),
    ('Family and Consumer Science', 'Fashion construction'),
    ('Family and Consumer Science', 'Home economics'),
    ('Family and Consumer Science', 'Interior design'),
    ('Family and Consumer Science', 'Nutrition'),
    ('Foreign Language', 'American Sign Language'),
    ('Foreign Language', 'Ancient Greek'),
    ('Foreign Language', 'Arabic'),
    ('Foreign Language', 'Chinese'),
    ('Foreign Language', 'French'),
    ('Foreign Language', 'German'),
    ('Foreign Language', 'Hebrew'),
    ('Foreign Language', 'Italian'),
    ('Foreign Language', 'Japanese'),
    ('Foreign Language', 'Korean'),
    ('Foreign Language', 'Latin'),
    ('Foreign Language', 'Portuguese'),
    ('Foreign Language', 'Russian'),
    ('Foreign Language', 'Spanish'),
    ('Foreign Language', 'AP Chinese Language and Culture'),
    ('Foreign Language', 'AP French Language and Culture'),
    ('Foreign Language', 'AP German Language and Culture'),
    ('Foreign Language', 'AP Italian Language and Culture'),
    ('Foreign Language', 'AP Japanese Language and Culture'),
    ('Foreign Language', 'AP Latin'),
    ('Foreign Language', 'AP Spanish Language and Culture'),
    ('Foreign Language', 'AP Spanish Literature and Culture'),
    ('Math', 'Algebra 1'),
    ('Math', 'Algebra 2'),
    ('Math', 'Calculus'),
    ('Math', 'Computer math'),
    ('Math', 'Consumer math'),
    ('Math', 'Fundamentals of math'),
    ('Math', 'Geometry'),
    ('Math', 'Integrated math'),
    ('Math', 'Math applications'),
    ('Math', 'Multivariable calculus'),
    ('Math', 'Practical math'),
    ('Math', 'Pre-algebra'),
    ('Math', 'Pre-calculus'),
    ('Math', 'Probability'),
    ('Math', 'Quantitative literacy'),
    ('Math', 'Statistics'),
    ('Math', 'Trigonometry'),
    ('Math', 'AP Calculus AB'),
    ('Math', 'AP Calculus BC'),
    ('Math', 'AP Statistics'),
    ('Performing Arts', 'Choir'),
    ('Performing Arts', 'Concert band'),
    ('Performing Arts', 'Dance'),
    ('Performing Arts', 'Drama'),
    ('Performing Arts', 'Guitar'),
    ('Performing Arts', 'Jazz band'),
    ('Performing Arts', 'Marching band'),
    ('Performing Arts', 'Music theory'),
    ('Performing Arts', 'Orchestra'),
    ('Performing Arts', 'Percussion'),
    ('Performing Arts', 'Piano'),
    ('Performing Arts', 'Theater technology'),
    ('Performing Arts', 'World music'),
    ('Physical Education', 'Aerobics'),
    ('Physical Education', 'Dance'),
    ('Physical Education', 'Gymnastics'),
    ('Physical Education', 'Health'),
    ('Physical Education', 'Lifeguard training'),
    ('Physical Education', 'Pilates'),
    ('Physical Education', 'Racket sports'),
    ('Physical Education', 'Specialized sports'),
    ('Physical Education', 'Swimming'),
    ('Physical Education', 'Weight training'),
    ('Physical Education', 'Yoga'),
    ('Science', 'Agriculture'),
    ('Science', 'Astronomy'),
    ('Science', 'Biology'),
    ('Science', 'Botany'),
    ('Science', 'Chemistry'),
    ('Science', 'Earth science'),
    ('Science', 'Electronics'),
    ('Science', 'Environmental science'),
    ('Science', 'Environmental studies'),
    ('Science', 'Forensic science'),
    ('Science', 'Geology'),
    ('Science', 'Marine biology'),
    ('Science', 'Oceanography'),
    ('Science', 'Physical science'),
    ('Science', 'Physics'),
    ('Science', 'Zoology'),
    ('Science', 'AP Biology'),
    ('Science', 'AP Chemistry'),
    ('Science', 'AP Environmental Science'),
    ('Science', 'AP Physics C: Electricity and Magnetism'),
    ('Science', 'AP Physics 1: Algebra-Based'),
    ('Science', 'AP Physics 2: Algebra-Based'),
    ('Social Studies', 'Cultural anthropology'),
    ('Social Studies', 'Current events'),
    ('Social Studies', 'European history'),
    ('Social Studies', 'Geography'),
    ('Social Studies', 'Global studies'),
    ('Social Studies', 'Human geography'),
    ('Social Studies', 'International relations'),
    ('Social Studies', 'Law'),
    ('Social Studies', 'Macroeconomics'),
    ('Social Studies', 'Microeconomics'),
    ('Social Studies', 'Modern world studies'),
    ('Social Studies', 'Physical anthropology'),
    ('Social Studies', 'Political studies'),
    ('Social Studies', 'Psychology'),
    ('Social Studies', 'Religious studies'),
    ('Social Studies', 'Sociology'),
    ('Social Studies', 'US government'),
    ('Social Studies', 'US history'),
    ('Social Studies', "Women's studies"),
    ('Social Studies', 'World history'),
    ('Social Studies', 'World politics'),
    ('Social Studies', 'World religions'),
    ('Social Studies', 'AP Comparative government and politics'),
    ('Social Studies', 'AP European history'),
    ('Social Studies', 'AP Human Geography'),
    ('Social Studies', 'AP Macroeconomics'),
    ('Social Studies', 'AP Microeconomics'),
    ('Social Studies', 'AP Psychology'),
    ('Social Studies', 'AP United States Government and Politics'),
    ('Social Studies', 'AP United States History'),
    ('Social Studies', 'AP World History'),
    ('Visual Arts', '3-D art'),
    ('Visual Arts', 'Art history'),
    ('Visual Arts', 'Ceramics'),
    ('Visual Arts', 'Digital media'),
    ('Visual Arts', 'Drawing'),
    ('Visual Arts', 'Film production'),
    ('Visual Arts', 'Jewelry design'),
    ('Visual Arts', 'Painting'),
    ('Visual Arts', 'Photography'),
    ('Visual Arts', 'Printmaking'),
    ('Visual Arts', 'Sculpture'),
    ('Vocational Education', 'Auto body repair'),
    ('Vocational Education', 'Auto mechanics'),
    ('Vocational Education', 'Building construction'),
    ('Vocational Education', 'Computer-aided drafting'),
    ('Vocational Education', 'Cosmetology'),
    ('Vocational Education', 'Criminal justice'),
    ('Vocational Education', 'Driver education'),
    ('Vocational Education', 'Electronics'),
    ('Vocational Education', 'FFA (Future Farmers of America)'),
    ('Vocational Education', 'Fire science'),
    ('Vocational Education', 'Heating and cooling systems'),
    ('Vocational Education', 'Hospitality and tourism'),
    ('Vocational Education', 'JROTC (Junior Reserve Officers\' Training Corps)'),
    ('Vocational Education', 'Metalworking'),
    ('Vocational Education', 'Networking'),
    ('Vocational Education', 'Plumbing'),
    ('Vocational Education', 'Production technology'),
    ('Vocational Education', 'Refrigeration fundamentals'),
    ('Vocational Education', 'Robotics'),
    ('Vocational Education', 'Woodworking')
]



# Insert the classes into the "classes" table
cursor.executemany('INSERT INTO classes (subject, class_name) VALUES (?, ?)', class_data)

# Commit the changes and close the connection
conn.commit()
conn.close()



