"""empty message

Revision ID: 262dccdd6c73
Revises: 7590e835ddbf
Create Date: 2023-06-16 02:31:13.532326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262dccdd6c73'
down_revision = '7590e835ddbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.INTEGER(), nullable=True))
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
